//! Interactive setup wizard.

use std::path::PathBuf;

use dialoguer::{theme::ColorfulTheme, Confirm, Input, Select};

use crate::cli::output;
use crate::error::Result;

/// Run the interactive setup wizard.
pub fn execute(path: PathBuf, force: bool) -> Result<()> {
    output::header(env!("CARGO_PKG_VERSION"));
    println!("  Welcome to edgelord\n");
    println!("  Let's set up your configuration.\n");

    let theme = ColorfulTheme::default();

    // Network selection
    let networks = &["Testnet (recommended for first run)", "Mainnet"];
    let network = Select::with_theme(&theme)
        .with_prompt("Network")
        .items(networks)
        .default(0)
        .interact()?;

    let environment = if network == 0 { "testnet" } else { "mainnet" };

    // Strategy selection
    println!("\n  Strategies\n");

    let single_condition = Confirm::with_theme(&theme)
        .with_prompt("Enable single-condition (YES + NO < $1)")
        .default(true)
        .interact()?;

    let rebalancing = Confirm::with_theme(&theme)
        .with_prompt("Enable market-rebalancing (multi-outcome)")
        .default(true)
        .interact()?;

    let combinatorial = Confirm::with_theme(&theme)
        .with_prompt("Enable combinatorial (requires LLM API key)")
        .default(false)
        .interact()?;

    let mut enabled_strategies = Vec::new();
    if single_condition {
        enabled_strategies.push("single-condition");
    }
    if rebalancing {
        enabled_strategies.push("market-rebalancing");
    }
    if combinatorial {
        enabled_strategies.push("combinatorial");
    }

    // Risk settings
    println!("\n  Risk limits\n");

    let max_exposure: f64 = Input::with_theme(&theme)
        .with_prompt("Maximum total exposure ($)")
        .default(500.0)
        .interact()?;

    let max_position: f64 = Input::with_theme(&theme)
        .with_prompt("Maximum per-market position ($)")
        .default(100.0)
        .interact()?;

    // Generate config
    let config = generate_config(environment, &enabled_strategies, max_exposure, max_position);

    // Check if file exists
    if path.exists() && !force {
        let overwrite = Confirm::with_theme(&theme)
            .with_prompt(format!("{} already exists. Overwrite?", path.display()))
            .default(false)
            .interact()?;
        if !overwrite {
            println!("\n  Aborted.");
            return Ok(());
        }
    }

    // Write config
    std::fs::write(&path, config)?;

    println!();
    output::success(&format!("Created {}", path.display()));
    println!();
    println!("  Next steps:");
    println!("    1. Set EDGELORD_WALLET_KEY environment variable");
    println!(
        "    2. Run {} to validate",
        output::highlight("edgelord check live")
    );
    println!("    3. Run {} to start", output::highlight("edgelord run"));
    println!();

    Ok(())
}

fn generate_config(
    environment: &str,
    strategies: &[&str],
    max_exposure: f64,
    max_position: f64,
) -> String {
    let strategies_list = strategies
        .iter()
        .map(|s| format!("\"{}\"", s))
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"# Edgelord configuration
# Generated by `edgelord init`

[network]
environment = "{environment}"

[strategies]
enabled = [{strategies_list}]

[strategies.single-condition]
min_edge = 0.05
min_profit = 0.50

[strategies.market-rebalancing]
min_edge = 0.03

[risk]
max_exposure = {max_exposure}
max_position_per_market = {max_position}
max_slippage = 0.02

[notifications]
backend = "none"

[database]
path = "edgelord.db"

[governor]
enabled = true
target_latency_p99_ms = 100
"#
    )
}
